== kn-source-kamelet

`kn-source-kamelet` Knative eventing sources plugin manages Kamelet sources on your cluster.

=== Description

With this plugin, you can list available Kamelets and use those in KameletBindings as Knative eventing sources.

=== Usage

----
Manages Kamelets and KameletBindings as Knative eventing sources.

Usage:
  kn source kamelet [command]

Available Commands:
  help        Help about any command
  list        List available Kamelet sources
  version     Prints the plugin version

Flags:
  -h, --help   help for kn-plugin-source-kamelet

Use "kn-source-kamelet [command] --help" for more information about a command.
----

==== `kn source kamelet list`

----
List available Kamelet sources

Usage:
  kn source kamelet list [flags]

Flags:
  -h, --help   help for list
----

==== `kn source kamelet version`

This command prints out the version of this plugin and all extra information which might help, for example when creating
bug reports.

----
Prints the plugin version

Usage:
  kn source kamelet version [flags]

Flags:
  -h, --help   help for version
----

=== Examples

==== List available Kamelet sources

You want to list all available Kamelets on your cluster.
In this case, you can use the `kn source kamelet list` command.

.List Kamelet sources
====
----
$ kn source kamelet list

Kamelet_1
Kamelet_2
Kamelet_3
----
====

==== Print out the version of this plugin

The `kn source kamelet version` command helps you to identify the version of this plugin.

.Version output
=====
-----
$ kn source kamelet version

Version:      v20200402-local-a099aaf-dirty
Build Date:   2020-04-02 18:16:20
Git Revision: a099aaf
-----
=====

As you can see it prints out the version, (or a generated timestamp when this plugin is built from a non-released commit)
the date when the plugin has been built and the actual Git revision.
